#!/bin/bash

cd /var/www/html/rabbit/tut2/

php runspam.php;

# php new_task.php vasile$i..;
# php new_task.php vasile....
# php new_task.php vasile...
# php new_task.php vasile.......
# php new_task.php vasile..
# php new_task.php vasile....
# php new_task.php vasile......
# php new_task.php vasile....
# php new_task.php vasile.....
# php new_task.php vasile...........
# php new_task.php vasile.......
# php new_task.php vasile....
# php new_task.php vasile.....
# php new_task.php vasile.........
# php new_task.php vasile....
# php new_task.php vasile.......
# php new_task.php vasile......
# php new_task.php vasile........
# php new_task.php vasile...
