#!/bin/bash

cd /var/www/html/rabbit

php new_task.php vasile....
php new_task.php vasile...
php new_task.php vasile.......
php new_task.php vasile..
php new_task.php vasile....
php new_task.php vasile......
php new_task.php vasile....
php new_task.php vasile.....
php new_task.php vasile...........
php new_task.php vasile.......
php new_task.php vasile....
php new_task.php vasile.....
php new_task.php vasile.........
php new_task.php vasile....
php new_task.php vasile.......
php new_task.php vasile......
php new_task.php vasile........
php new_task.php vasile...
